#!/usr/bin/env python

import argparse
import sys

PATH = "content/discography/changes.md"

parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument(
    "--issue",
)
parser.add_argument(
    "change",
)

args = parser.parse_args()

change = args.change
if args.issue:
    change = "{{< issue %s >}}%s{{< /issue >}}" % (args.issue, change)
change = "* " + change

lines = list(open(PATH))

found_star = False
for idx, line in enumerate(lines):
    if not found_star and line.startswith("*"):
        found_star = True

    if not line.strip() and found_star:
        break

lines.insert(idx, change + "\n")

open(PATH, "w").write("".join(lines))
