name: Style PHP-CS-Fixer

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  style:
   runs-on: ubuntu-22.04
   steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Generate
        run: ./tools/database.py normalise --no-scrape-discogs

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Run normalise
